### ISSUE TITLE
androidTestMock : No tests were found error, "Empty Test Suite"

### ISSUE THREAD

**Issue by jimandreas** [googlecodelabs/android-testing#27]
I am hitting this error at the following codelab step:

[Espresso test 3: Clicking a note](https://codelabs.developers.google.com/codelabs/android-testing/#6)

The Android studio setup is shown in the snips below on Windows 7.   I have not found a solution for this problem.   It appears that the use of the "AndroidTestMock" facility is not in wide use - and so there is little to be found out there for guidance.   Hmm.

![image](https://cloud.githubusercontent.com/assets/15666465/15111058/edb06cfe-15e4-11e6-9707-ab51b34e0014.png)

![image](https://cloud.githubusercontent.com/assets/15666465/15111035/ce870b76-15e4-11e6-88cf-161cfe725deb.png)

    Process finished with exit code 1
    Class not found: "com.example.android.testing.notes.notedetail.NoteDetailScreenTest"Empty test suite.

**Comment by slinzner** [comment]
Unfortunately I cannot reproduce this issue. Do you mind sending me the logcat for the test run?

**Comment by jimandreas** [comment]
There wasn't anything in the logcat when I asked studio to run ONLY the NoteDetailScreenTest.   

Same error:   "No tests were found"

OK I will ask it to run everything in the AndroidTestMock category.   Well that was interesting.   It did more stuff but *ALSO* ran tests in "androidTest":

![image](https://cloud.githubusercontent.com/assets/15666465/15223629/bc92888a-1875-11e6-845f-334300a7deb8.png)

with this result:

![image](https://cloud.githubusercontent.com/assets/15666465/15223731/31bf9ada-1876-11e6-8caa-26ab69a6c93d.png)

and this logcat:

[logcat.txt](https://github.com/googlecodelabs/android-testing/files/261896/logcat.txt)

****  and with this test output:

Testing started at 7:18 PM ...

05/12 19:18:17: Launching Tests in 'com.example.android.testing.notes'
$ adb push C:\Users\Jim\Desktop\AS-active\android-testing-step-7\app\build\outputs\apk\app-mock-debug.apk /data/local/tmp/com.example.android.testing.notes.mock
$ adb shell pm install -r "/data/local/tmp/com.example.android.testing.notes.mock"
	pkg: /data/local/tmp/com.example.android.testing.notes.mock
Success


$ adb push C:\Users\Jim\Desktop\AS-active\android-testing-step-7\app\build\outputs\apk\app-mock-debug-androidTest-unaligned.apk /data/local/tmp/com.example.android.testing.notes.mock.test
$ adb shell pm install -r "/data/local/tmp/com.example.android.testing.notes.mock.test"
	pkg: /data/local/tmp/com.example.android.testing.notes.mock.test
Success


Running tests

$ adb shell am instrument -w -r   -e package com.example.android.testing.notes -e debug false com.example.android.testing.notes.mock.test/android.support.test.runner.AndroidJUnitRunner
Client not ready yet..Test running started

java.lang.AssertionError: Implement in step 8
at org.junit.Assert.fail(Assert.java:88)
at com.example.android.testing.notes.addnote.AddNoteScreenTest.addImageToNote_ShowsThumbnailInUi(AddNoteScreenTest.java:87)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)


android.support.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'with text: is "ATSL"' doesn't match the selected view.
Expected: with text: is "ATSL"
Got: "AppCompatTextView{id=2131492989, res-name=note_detail_title, visibility=VISIBLE, width=0, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=32.0, y=288.0, text=, input-type=0, ime-target=false, has-links=false}"

at dalvik.system.VMStack.getThreadStackTrace(Native Method)
at java.lang.Thread.getStackTrace(Thread.java:580)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:82)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:53)
at android.support.test.espresso.ViewInteraction.runSynchronouslyOnUiThread(ViewInteraction.java:184)
at android.support.test.espresso.ViewInteraction.check(ViewInteraction.java:158)
at com.example.android.testing.notes.notedetail.NoteDetailScreenTest.noteDetails_DisplayedInUi(NoteDetailScreenTest.java:107)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: junit.framework.AssertionFailedError: 'with text: is "ATSL"' doesn't match the selected view.
Expected: with text: is "ATSL"
Got: "AppCompatTextView{id=2131492989, res-name=note_detail_title, visibility=VISIBLE, width=0, height=59, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=32.0, y=288.0, text=, input-type=0, ime-target=false, has-links=false}"

at android.support.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:1014)
at android.support.test.espresso.assertion.ViewAssertions$2.check(ViewAssertions.java:89)
at android.support.test.espresso.ViewInteraction$2.run(ViewInteraction.java:170)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)


java.lang.AssertionError: Implement step 9
at org.junit.Assert.fail(Assert.java:88)
at com.example.android.testing.notes.notes.AppNavigationTest.clickOnAndroidHomeIcon_OpensNavigation(AppNavigationTest.java:83)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)


java.lang.AssertionError: Implement step 9
at org.junit.Assert.fail(Assert.java:88)
at com.example.android.testing.notes.notes.AppNavigationTest.clickOnStatisticsNavigationItem_ShowsStatisticsScreen(AppNavigationTest.java:65)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:257)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)

Tests ran to completion.

**Comment by jimandreas** [comment]
Oh yes in case there are questions - here is my NoteDetailScreenTest.java renamed as a .txt file for Githup importing:

[NoteDetailScreenTest.txt](https://github.com/googlecodelabs/android-testing/files/261925/NoteDetailScreenTest.txt)

**Comment by slinzner** [comment]
I cannot reproduce the "no tests found" error on my machine, can you give me more details, ie. Android Studio version and device/api level combination you're running this on? Can you also confirm that you are using the correct run configuration for instrumentation and not the unit test configuration?

Running tests in the "androidMockTest" variant source set will also run tests in the androidTest source set. That's the expected behavior since a flavors are just overlays over a base source set, like "main" or "androidTest".

For the failing tests, when running tests in "androidMockTest", what I can see from the log is that the  tests fail because you haven't implemented step-8/step-9 yet. If you look closely you will spot an assertion error: "java.lang.AssertionError: Implement in step 8/Implement in step 9". So following the instructions and implement all the steps should fix those failing tests. In this case it also seems like NoteDetailScreenTest is picked up and run, which leads me to believe that the "no found error" could be using the wrong run configuration.

Please also make sure you have animations turned off, on your device and emulator, to avoid random flakiness of tests.

**Comment by slinzner** [comment]
I was able to reproduce the issue on my other machine and it confirmed my suspicion. The error you're seeing happens if AS for some reason thinks that the test that you're about to run is a unit and not an instrumentation test. Often this error goes away buy just clicking on the package instead of the actual class. I added instructions to the trouble shooting section of the codelab with a screenshot to make it clear how to recover from this issue.

**Comment by jimandreas** [comment]
Thank you, confirmed.   If I click on the *package* and not the *test*, then AS does find the test and executes it.   This unblocks my progress.   I can now proceed further with the codelab!    Cheers, Jim A
![image](https://cloud.githubusercontent.com/assets/15666465/15256130/51ea03f2-1940-11e6-8a8f-34386b5ca985.png)

**Comment by jimandreas** [comment]
UPDATE:  at the step-9 branch now, repeating the same workaround that functioned at step-7, has STOPPED WORKING.  Now the workaround for running the NoteDetailScreenTest, which was to run the test at the package level, on my windows 7 system with Latest and Greatest Studio versions:

fails at the unit test
fails at the notedetail package
fails at the com.example.android.testing.notes package level

Note that the work around continues to work in the step-7.   The one significant code difference from the diffs that I can see is that the step-9 branch uses:

    import android.support.test.filters.LargeTest;

while the step-7 branch uses:

    import android.test.suitebuilder.annotation.LargeTest;

screenshot of failure at step-9:

![image](https://cloud.githubusercontent.com/assets/15666465/15355422/db8503cc-1cf2-11e6-81be-5fec6be40fda.png)

**Comment by IgorGanapolsky** [comment]
I am still getting the error: **Empty test suite**.  I am using `MockitoJUnitRunner`.  Is that what's causing it?

**Comment by jimandreas** [comment]
Just curious - are you running Android Studio on a Windows computer?    I found this bug report and fix and reported it to StackOverflow.   It might help:

http://stackoverflow.com/a/39959187/3853712

**Comment by IgorGanapolsky** [comment]
@jimandreas Running on Mac.

**Comment by mzhua** [comment]
I had this error before, and after run ./gradlew testDebugUnitTest in command first, the error gone.

**Comment by giorgosioak** [comment]
Happens when you try to run "node in app" and not "app" :)

![Uploading db8503cc-1cf2-11e6-81be-5fec6be40fda.png…]()

**Comment by jrcinco** [comment]
The fix on Android Studio is:
step 1.- Go to Run/Debug configuration
step 2.- Go to Android Tests section
step 3.- Remove the test configuration file with (-)
step 4.- Press Apply and OK
step 5.- Run the test again
