### ISSUE TITLE
com.android.dex.DexException when executing CodeCoverage task

### ISSUE THREAD

**Issue by cpeppas** [googlecodelabs/android-testing#6]
On master branch executing 

./gradlew createMockDebugCoverageReport

produces the following

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/design/R$anim;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)

Btw..Great codelab! Thanks for sharing.

**Comment by slinzner** [comment]
Thanks! I cannot reproduce this issue with the latest Android Gradle plugin and build tools. Note, that this tasked has been renamed to: create<Variant>AndroidTestCoverageReport starting from version 1.3. See this [bug](https://code.google.com/p/android/issues/detail?id=178551) for details.
