### ISSUE TITLE
Step 7 - addNoteToNotesList() fails on "Error performing 'scroll RecyclerView to:..."

### ISSUE THREAD

**Issue by urig** [googlecodelabs/android-testing#95]
### Steps to reproduce:
1. Use Android Studio 3.1.4 on Windows. Run the tests on a software emulator for Nexus 5X API 28  (Android 9, API 28)
2. Follow the instructions in https://codelabs.developers.google.com/codelabs/android-testing/index.html#6 up until before the title "Espresso test 3: Clicking a note". 
3. Run the "Tests in 'com.example.android.testing.notes'" test suite as per instructions.

### Expected behavior:
The test `addNoteToNotesList()` should pass.

### Actual behavior:
The test fails with the following stack trace:

>android.support.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: has descendant: with text: is "UI testing for Android"' on view 'with id: com.example.android.testing.notes:id/notes_list'.
at android.support.test.espresso.PerformException$Builder.build(PerformException.java:82)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:79)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
at android.support.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:173)
at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:114)
at com.example.android.testing.notes.notes.NotesScreenTest.addNoteToNotesList(NotesScreenTest.java:127)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.RuntimeException: Found 0 items matching holder with view: has descendant: with text: is "UI testing for Android", but position -1 was requested.
at android.support.test.espresso.contrib.RecyclerViewActions$ScrollToViewAction.perform(RecyclerViewActions.java:361)
at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:248)
at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:63)
at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:153)
at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:150)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Note:
When running only the `addNoteToNotesList()` without any other tests, it passes.

**Comment by HassanAlizadehDevlab** [comment]
@urig 
Its about animation. If you want to pass this test you have to turn on "Animator duration scale" in developer options

**Comment by HassanAlizadehDevlab** [comment]
> ### Steps to reproduce:
> 1. Use Android Studio 3.1.4 on Windows. Run the tests on a software emulator for Nexus 5X API 28  (Android 9, API 28)
> 2. Follow the instructions in https://codelabs.developers.google.com/codelabs/android-testing/index.html#6 up until before the title "Espresso test 3: Clicking a note".
> 3. Run the "Tests in 'com.example.android.testing.notes'" test suite as per instructions.
> 
> ### Expected behavior:
> The test `addNoteToNotesList()` should pass.
> 
> ### Actual behavior:
> The test fails with the following stack trace:
> 
> > android.support.test.espresso.PerformException: Error performing 'scroll RecyclerView to: holder with view: has descendant: with text: is "UI testing for Android"' on view 'with id: com.example.android.testing.notes:id/notes_list'.
> > at android.support.test.espresso.PerformException$Builder.build(PerformException.java:82)
> > at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:79)
> > at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
> > at android.support.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:312)
> > at android.support.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:173)
> > at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:114)
> > at com.example.android.testing.notes.notes.NotesScreenTest.addNoteToNotesList(NotesScreenTest.java:127)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> > at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> > at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> > at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> > at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
> > at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> > at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> > at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> > at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> > at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> > at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
> > at org.junit.runners.Suite.runChild(Suite.java:128)
> > at org.junit.runners.Suite.runChild(Suite.java:27)
> > at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> > at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> > at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> > at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> > at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> > at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> > at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> > at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
> > at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
> > at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
> > at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
> > Caused by: java.lang.RuntimeException: Found 0 items matching holder with view: has descendant: with text: is "UI testing for Android", but position -1 was requested.
> > at android.support.test.espresso.contrib.RecyclerViewActions$ScrollToViewAction.perform(RecyclerViewActions.java:361)
> > at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:356)
> > at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:248)
> > at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:63)
> > at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:153)
> > at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:150)
> > at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> > at android.os.Handler.handleCallback(Handler.java:873)
> > at android.os.Handler.dispatchMessage(Handler.java:99)
> > at android.os.Looper.loop(Looper.java:193)
> > at android.app.ActivityThread.main(ActivityThread.java:6669)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 
> ### Note:
> When running only the `addNoteToNotesList()` without any other tests, it passes.

Its about animation. If you want to pass this test you have to turn on "Animator duration scale" in developer options

**Comment by urig** [comment]
@HassanAlizadehDevlab thanks. Do you mean turn **off**?

I'm asking because I now see the codelab instructions state:

> You need to turn off animations on your test device (or emulator), otherwise Espresso may not work as expected and your tests may fail. Turn off animations from Settings by opening Developer Options and turning all the following options under "Drawing" off:
>
>    Window animation scale
>    Transition animation scale
>    Animator duration scale

**Comment by corinzio** [comment]
I have the same problem even after i setting off the animations, i think is something wrong with EspressoIdlingResource, i had to add a Thread.sleep(3000) between the save note and the recyclerview search of the "UI testing for Android" note on NoteScreenTest.java

**Comment by corinzio** [comment]
I had to add this @Before (copied from Mock source)
```java
    /**
     * Prepare your test fixture for this test. In this case we register an IdlingResources with
     * Espresso. IdlingResource resource is a great way to tell Espresso when your app is in an
     * idle state. This helps Espresso to synchronize your test actions, which makes tests significantly
     * more reliable.
     */
    @Before
    public void registerIdlingResource() {
        IdlingRegistry.getInstance().register(
                mNotesActivityTestRule.getActivity().getCountingIdlingResource()
        );
    }
```

in order to register the idling resource and be able to remove the Thread.sleep instruction

**Comment by helloworld10010** [comment]
> I had to add this @before (copied from Mock source)
> 
> ```java
>     /**
>      * Prepare your test fixture for this test. In this case we register an IdlingResources with
>      * Espresso. IdlingResource resource is a great way to tell Espresso when your app is in an
>      * idle state. This helps Espresso to synchronize your test actions, which makes tests significantly
>      * more reliable.
>      */
>     @Before
>     public void registerIdlingResource() {
>         IdlingRegistry.getInstance().register(
>                 mNotesActivityTestRule.getActivity().getCountingIdlingResource()
>         );
>     }
> ```
> 
> in order to register the idling resource and be able to remove the Thread.sleep instruction

happy!
